[workspace]
members = ["client", "json"]
exclude = ["integration_test", "regtest"]
resolver = "2"

[patch.crates-io.bitcoind-json-rpc-client]
path = "client"

[patch.crates-io.bitcoind-json-rpc-types]
path = "json"
