[workspace]
members = ["client", "types", "jsonrpc", "verify"]
exclude = ["integration_test", "node"]
resolver = "2"

[patch.crates-io.corepc-client]
path = "client"

[patch.crates-io.corepc-types]
path = "types"

[patch.crates-io.jsonrpc]
path = "jsonrpc"
